version: "3.3"

services:
  redis:
    image: "redis:alpine"
    restart: on-failure
  mysql:
    image: "mysql:5.7"
    restart: on-failure
    environment: [ "MYSQL_ALLOW_EMPTY_PASSWORD=yes" ]
  server:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - "redis"
      - "mysql"
