version: "3.3"

services:
  redis:
    image: "redis"
    restart: on-failure
  mysql:
    image: "mysql"
    restart: on-failure
    environment: [ "MYSQL_ALLOW_EMPTY_PASSWORD=true" ]
  server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - "redis"
      - "mysql"
