version: "3.3"

services:
  redis:
    image: "redis"
    restart: on-failure
  mysql:
    image: "mysql"
    restart: on-failure
    env_file:
      - ./.env.docker
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: "phpmyadmin"
    restart: on-failure
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
  server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env.docker
    restart: on-failure
    depends_on:
      - "redis"
      - "mysql"

volumes:
  mysql-data:
